language: node_js
node_js:
  - "node"
services:
  - postgresql
before_script:
  - psql -c 'CREATE DATABASE gutsy_test;' -U postgres
after_success: 'npm run coveralls'
script:
  - yarn run lint
  - yarn test
