language: node_js
node_js:
  - "8"
addons:
    postgresql: "9.6"
services:
  - postgresql
before_script:
  - psql -c 'CREATE DATABASE gutsy_test;' -U postgres
  - yarn global add node-gyp
script:
  - yarn lint
  - yarn test-cover
  - yarn test-coverage
after_script: yarn run coveralls
